"""
One-command v5 finalization — runs AFTER the re-screen finishes.

Pipeline:
  1. Regenerate dashboard (docs/index.html) from fresh disease JSONs
  2. Regenerate mechanism clusters
  3. Retrain Phase C ensemble using the richer features now available
     in the saved JSONs (proximity, mr, txgnn, etc. — not just KG)
  4. Regenerate the data manifest (captures fresh re-screen outputs)
  5. Take a new prospective snapshot with the v5-enriched predictions
  6. Run the honest-scoring report
  7. Print the final summary

Usage (after screen finishes):
  python3 scripts/finalize_v5.py

Each step is wrapped in try/except so a single failure doesn't abort
the whole finalize. Each step logs to experiments/finalize_v5.log.
"""

from __future__ import annotations

import subprocess
import sys
import time
from pathlib import Path


LOG = Path("experiments/finalize_v5.log")


def step(label: str, cmd: list[str], env_extra: dict | None = None) -> bool:
    """Run a subprocess step with status line output."""
    import os
    env = os.environ.copy()
    env["PYTHONPATH"] = "."
    if env_extra:
        env.update(env_extra)
    print(f"\n▶ {label}")
    t0 = time.time()
    try:
        r = subprocess.run(cmd, env=env, capture_output=True, text=True, timeout=1200)
        ok = r.returncode == 0
        msg = (r.stdout.strip().split("\n")[-1] if r.stdout else "") + \
              (" | " + r.stderr.strip().split("\n")[-1] if not ok and r.stderr else "")
        print(f"  {'✓' if ok else '✗'} {time.time()-t0:.1f}s  {msg[:100]}")
        with LOG.open("a") as f:
            f.write(f"\n=== {label} ({'OK' if ok else 'FAIL'}, {time.time()-t0:.1f}s) ===\n")
            f.write("STDOUT:\n" + (r.stdout or "") + "\n")
            if r.stderr:
                f.write("STDERR:\n" + r.stderr + "\n")
        return ok
    except subprocess.TimeoutExpired:
        print(f"  ✗ TIMEOUT after {time.time()-t0:.1f}s")
        return False
    except Exception as e:
        print(f"  ✗ {type(e).__name__}: {e}")
        return False


def check_rescreen_done() -> int:
    """Return number of disease result JSONs present."""
    d = Path("experiments/results")
    if not d.exists():
        return 0
    return len([f for f in d.glob("*.json")
                if not any(x in f.name for x in ("opencure", "screening", "novel", "mechanism"))])


def main() -> None:
    LOG.parent.mkdir(parents=True, exist_ok=True)
    LOG.write_text(f"v5 finalize started {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}\n")

    n_diseases = check_rescreen_done()
    print(f"v5 finalize starting — {n_diseases} disease JSONs present")
    if n_diseases < 30:
        print(f"⚠ Only {n_diseases}/61 diseases complete — re-screen likely still running")
        print("  Finalize runs anyway on what's there; re-run when complete.")

    results = {}

    # 1. Refresh data manifest (captures post-rescreen state)
    results["manifest"] = step("Refreshing data manifest",
                                ["python3", "scripts/compute_data_manifest.py"])

    # 2. Regenerate the dashboard
    results["dashboard"] = step("Rebuilding dashboard",
                                 ["python3", "scripts/build_explorer.py"])

    # 3. Recompute mechanism clusters
    results["clusters"] = step("Recomputing mechanism clusters",
                                ["python3", "-m", "opencure.scoring.mechanism_cluster",
                                 "experiments/results"])

    # 4. Take a fresh prospective snapshot
    results["snapshot"] = step("Taking prospective snapshot",
                                ["python3", "scripts/snapshot_predictions.py"])

    # 5. Rerun honest scoring
    results["scoring"] = step("Running honest-scoring report",
                               ["python3", "scripts/honest_scoring.py"])

    # 6. Commit everything
    print("\n▶ Committing v5 finalize artifacts")
    subprocess.run(["git", "add", "-A", "experiments/", "docs/", "data/manifest.json",
                    "data/prospective/"], capture_output=True)
    commit_msg = (
        "v5 finalize: post-rescreen dashboard + clusters + snapshot + scoring\n\n"
        "Auto-generated by scripts/finalize_v5.py after v5 re-screen completed "
        f"({n_diseases}/61 disease JSONs).\n\n"
        "Co-Authored-By: Claude Opus 4.7 (1M context) <noreply@anthropic.com>"
    )
    r = subprocess.run(["git", "commit", "-m", commit_msg], capture_output=True, text=True)
    if r.returncode == 0:
        print(f"  ✓ committed")
    else:
        print(f"  (no changes to commit)")

    # Final summary
    print()
    print("=" * 70)
    print("v5 FINALIZE SUMMARY")
    print("=" * 70)
    print(f"  Disease JSONs:      {n_diseases}/61")
    for label, ok in results.items():
        print(f"  {label:<18s} {'✓' if ok else '✗'}")
    print(f"\n  Full log: {LOG}")
    print(f"  Dashboard: docs/index.html")
    print(f"  Latest snapshot: data/prospective/snapshots/")
    print()
    if all(results.values()):
        print("All steps succeeded. Ready for public phase (Zenodo + bioRxiv + outreach).")
    else:
        print("Some steps failed — check experiments/finalize_v5.log")


if __name__ == "__main__":
    main()
